import type { Influencer } from '@/types/influencer'
import type { Campana } from '@/types/campana'
import type { Marca } from '@/types/marca'

function iniciales(nombre: string): string {
  return nombre.split(' ').slice(0, 2).map(p => p[0]).join('').toUpperCase() || '?'
}

export const MOCK_INFLUENCERS: Influencer[] = [
  { id: 101, nombre: 'Camila Rojas', categoria: 'Moda', seguidores: 890000, engagement: 5.8, iniciales: iniciales('Camila Rojas'), estado: 'top', bio: 'Editora de moda y amante del streetwear latino. Colaboro con marcas que tienen algo que decir.', ubicacion: 'Santiago, Chile', redes: { instagram: 'camirojas', tiktok: 'camirojas' } },
  { id: 102, nombre: 'Benjamín Torres', categoria: 'Fitness', seguidores: 345000, engagement: 7.2, iniciales: iniciales('Benjamín Torres'), estado: 'top', bio: 'Entrenador personal certificado. Rutinas caseras sin equipo y nutrición simple.', ubicacion: 'Valparaíso, Chile', redes: { instagram: 'benjatorresfit', youtube: 'benjatorres' } },
  { id: 103, nombre: 'Valentina Paredes', categoria: 'Gastronomía', seguidores: 215000, engagement: 6.4, iniciales: iniciales('Valentina Paredes'), estado: 'disponible', bio: 'Cocinera casera. Recetas chilenas con vuelta de tuerca.', ubicacion: 'Concepción, Chile', redes: { instagram: 'valecocina', tiktok: 'valecocina' } },
  { id: 104, nombre: 'Diego Fuentes', categoria: 'Tech', seguidores: 520000, engagement: 4.9, iniciales: iniciales('Diego Fuentes'), estado: 'en-campaña', bio: 'Reviews de hardware y software en español neutro. 10 años probando gadgets.', ubicacion: 'Ciudad de México, México', redes: { instagram: 'diegotech', youtube: 'diegotech', twitter: 'diegotech' } },
  { id: 105, nombre: 'Antonia Silva', categoria: 'Viajes', seguidores: 180000, engagement: 8.1, iniciales: iniciales('Antonia Silva'), estado: 'top', bio: 'Viajera full-time. Rutas, tips y destinos escondidos de Sudamérica.', ubicacion: 'Buenos Aires, Argentina', redes: { instagram: 'antorutas', tiktok: 'antorutas' } },
  { id: 106, nombre: 'Martín Vargas', categoria: 'Gaming', seguidores: 720000, engagement: 6.8, iniciales: iniciales('Martín Vargas'), estado: 'disponible', bio: 'Streamer de FPS y estrategia. Partidas en vivo y análisis de lanzamientos.', ubicacion: 'Lima, Perú', redes: { instagram: 'martinvg', twitter: 'martinvg' } },
  { id: 107, nombre: 'Sofía Ramírez', categoria: 'Moda', seguidores: 95000, engagement: 9.2, iniciales: iniciales('Sofía Ramírez'), estado: 'top', bio: 'Moda sostenible y second-hand. Estilo consciente sin sacrificar lo bueno.', ubicacion: 'Bogotá, Colombia', redes: { instagram: 'sofiramirez', tiktok: 'sofiramirez' } },
  { id: 108, nombre: 'Matías López', categoria: 'Fitness', seguidores: 68000, engagement: 5.3, iniciales: iniciales('Matías López'), estado: 'disponible', bio: 'Running y triatlón. Planes de entreno para quien recién arranca.', ubicacion: 'Santiago, Chile', redes: { instagram: 'matirunner' } },
  { id: 109, nombre: 'Isidora Muñoz', categoria: 'Gastronomía', seguidores: 430000, engagement: 6.0, iniciales: iniciales('Isidora Muñoz'), estado: 'en-campaña', bio: 'Pastelería artesanal y panes de masa madre. Recetas probadas 20+ veces antes de publicar.', ubicacion: 'Viña del Mar, Chile', redes: { instagram: 'isicocina', youtube: 'isicocina' } },
  { id: 110, nombre: 'Felipe Castro', categoria: 'Tech', seguidores: 145000, engagement: 4.2, iniciales: iniciales('Felipe Castro'), estado: 'disponible', bio: 'Dev y entusiasta de la productividad. Apps, setups y automatización.', ubicacion: 'Santiago, Chile', redes: { instagram: 'felicastro', youtube: 'felicastro' } },
  { id: 111, nombre: 'Javiera Morales', categoria: 'Viajes', seguidores: 310000, engagement: 7.5, iniciales: iniciales('Javiera Morales'), estado: 'top', bio: 'Mochilera low-cost. He viajado 40 países con menos de 1K USD al mes.', ubicacion: 'São Paulo, Brasil', redes: { instagram: 'javitrotamundos', tiktok: 'javitrotamundos' } },
  { id: 112, nombre: 'Tomás Herrera', categoria: 'Gaming', seguidores: 1200000, engagement: 3.8, iniciales: iniciales('Tomás Herrera'), estado: 'top', bio: 'Gameplays de lanzamientos triple A. 3M de vistas mensuales en YouTube.', ubicacion: 'Ciudad de México, México', redes: { youtube: 'tomasplays', twitter: 'tomasplays' } },
  { id: 113, nombre: 'Constanza Pérez', categoria: 'Moda', seguidores: 42000, engagement: 8.7, iniciales: iniciales('Constanza Pérez'), estado: 'disponible', bio: 'Inclusive fashion y body positivity. Todas las tallas, todo el estilo.', ubicacion: 'Santiago, Chile', redes: { instagram: 'coniperez', tiktok: 'coniperez' } },
  { id: 114, nombre: 'Rodrigo Aguilar', categoria: 'Fitness', seguidores: 560000, engagement: 5.9, iniciales: iniciales('Rodrigo Aguilar'), estado: 'en-campaña', bio: 'Crossfit y calistenia. Rutinas intensas para atletas avanzados.', ubicacion: 'Medellín, Colombia', redes: { instagram: 'rodriaguilar', youtube: 'rodriaguilar' } },
  { id: 115, nombre: 'Francisca Navarro', categoria: 'Tech', seguidores: 260000, engagement: 6.7, iniciales: iniciales('Francisca Navarro'), estado: 'disponible', bio: 'Mujeres en tech. Carrera, herramientas y mentoría para quienes recién empiezan.', ubicacion: 'Santiago, Chile', redes: { instagram: 'francinav', twitter: 'francinav' } },
]

export const MOCK_MARCAS: Marca[] = [
  { id: 201, nombre: 'Movistar', descripcion: 'Telco líder en LATAM. Buscamos creadores que cuenten historias auténticas sobre conexión, tecnología y vida digital.', ubicacion: 'Santiago, Chile', iniciales: 'MV', categorias: ['Tech', 'Lifestyle'], profile_id: '00000000-0000-0000-0000-000000000201' },
  { id: 202, nombre: 'Falabella', descripcion: 'Retail con presencia en 7 países. Colaboramos con influencers de moda, hogar y tecnología para campañas estacionales.', ubicacion: 'Santiago, Chile', iniciales: 'FB', categorias: ['Moda', 'Lifestyle'], profile_id: '00000000-0000-0000-0000-000000000202' },
  { id: 203, nombre: 'Sodimac', descripcion: 'Mejoramiento del hogar. Proyectos DIY, jardín y soluciones prácticas con comunidad.', ubicacion: 'Santiago, Chile', iniciales: 'SD', categorias: ['Lifestyle', 'Viajes'], profile_id: '00000000-0000-0000-0000-000000000203' },
  { id: 204, nombre: 'Mercado Libre', descripcion: 'La plataforma de e-commerce más grande de LATAM. Conectamos con creators de todas las categorías.', ubicacion: 'Buenos Aires, Argentina', iniciales: 'ML', categorias: ['Tech', 'Moda', 'Gaming'], profile_id: '00000000-0000-0000-0000-000000000204' },
  { id: 205, nombre: 'Cencosud', descripcion: 'Holding retail con Jumbo, Paris y Easy. Campañas de food, fashion y home.', ubicacion: 'Santiago, Chile', iniciales: 'CS', categorias: ['Gastronomía', 'Moda'], profile_id: '00000000-0000-0000-0000-000000000205' },
  { id: 206, nombre: 'LATAM Airlines', descripcion: 'Conectamos LATAM con el mundo. Buscamos viajeros que inspiren nuevos destinos.', ubicacion: 'Santiago, Chile', iniciales: 'LT', categorias: ['Viajes'], profile_id: '00000000-0000-0000-0000-000000000206' },
]

export const MOCK_CAMPANAS: Campana[] = [
  { id: 301, marca: 'Movistar', titulo: 'Nueva línea 5G — Embajadores tech', descripcion: 'Buscamos 3 creadores tech para testear y reseñar el plan 5G+ durante 30 días. Contenido en IG Reels + review largo en YouTube.\n\nEntregas: 2 reels, 1 video review, 3 stories con experiencia real.', categoria: 'Tech', presupuesto: '$1.500–$3.000 USD', iniciales: 'MV', estado: 'activa', seguidoresMin: 100000, engagementMin: 4, brandId: 201 },
  { id: 302, marca: 'Falabella', titulo: 'Colección primavera-verano 2025', descripcion: 'Campaña estacional de moda. Look-books con 3 outfits de la nueva colección, estilo editorial.\n\nEntregas: 1 carrusel (8 fotos) + 2 stories con swipe-up a la tienda.', categoria: 'Moda', presupuesto: '$800–$2.000 USD', iniciales: 'FB', estado: 'activa', seguidoresMin: 50000, engagementMin: 5, brandId: 202 },
  { id: 303, marca: 'Sodimac', titulo: 'Proyecto DIY de primavera', descripcion: 'Transforma un rincón de tu casa con productos Sodimac. Paso a paso en video, sin guiones corporativos.\n\nLibertad creativa. Buscamos autenticidad.', categoria: 'Lifestyle', presupuesto: '$500–$1.200 USD', iniciales: 'SD', estado: 'activa', seguidoresMin: 30000, brandId: 203 },
  { id: 304, marca: 'Mercado Libre', titulo: 'Hot Sale 2025 — Gaming Setup', descripcion: 'Arma tu setup gamer ideal con productos de Mercado Libre. Video de unboxing + review de cada componente.\n\nEntregas: 1 video largo + 2 shorts.', categoria: 'Gaming', presupuesto: '$1.000–$2.500 USD', iniciales: 'ML', estado: 'activa', seguidoresMin: 200000, engagementMin: 4, brandId: 204 },
  { id: 305, marca: 'Cencosud', titulo: 'Recetas Jumbo — Verano en la mesa', descripcion: 'Creá 3 recetas originales con ingredientes Jumbo. Formato reel cocina rápida.\n\nIdeal para creadores de gastronomía con estilo casero.', categoria: 'Gastronomía', presupuesto: '$600–$1.500 USD', iniciales: 'CS', estado: 'activa', seguidoresMin: 80000, engagementMin: 5.5, brandId: 205 },
  { id: 306, marca: 'LATAM Airlines', titulo: 'Destinos escondidos de Sudamérica', descripcion: 'Viaje pagado a un destino menos conocido de la red LATAM. 7 días, todo cubierto. Contenido en video y fotos.\n\nEntregas: vlog 10+ min, 5 stories diarios, 1 reel highlights.', categoria: 'Viajes', presupuesto: '$3.000–$5.000 USD', iniciales: 'LT', estado: 'activa', seguidoresMin: 150000, engagementMin: 6, brandId: 206 },
  { id: 307, marca: 'Movistar', titulo: 'Campaña de retención — Testimonios reales', descripcion: 'Buscamos micro-influencers para compartir experiencias genuinas con el servicio. Formato casual, sin producción.', categoria: 'Lifestyle', presupuesto: '$300–$800 USD', iniciales: 'MV', estado: 'borrador', seguidoresMin: 15000, brandId: 201 },
  { id: 308, marca: 'Falabella', titulo: 'Beauty Week — Maquillaje express', descripcion: 'Lanzamiento de nueva línea de cosméticos. Tutoriales de 60 segundos mostrando 3 looks distintos.', categoria: 'Moda', presupuesto: '$500–$1.800 USD', iniciales: 'FB', estado: 'cerrada', seguidoresMin: 40000, brandId: 202 },
]
